name: build

on:
  schedule:
    - cron:  '1 1 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install prerequisites
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get -q update
          sudo apt-get install openjdk-11-jdk

      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Build
        run: |
          ./CI/build.sh
